<template>
  <svg
    viewBox="0 0 52 12"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle
      r="6"
      cx="6"
      cy="6"
      stroke="none"
    >
      <animate
        dur="1s"
        begin="0.1"
        values="0;1;0"
        attributeName="opacity"
        repeatCount="indefinite"
      />
    </circle>
    <circle
      r="6"
      cy="6"
      cx="26"
      stroke="none"
    >
      <animate
        dur="1s"
        begin="0.2"
        values="0;1;0"
        attributeName="opacity"
        repeatCount="indefinite"
      />
    </circle>
    <circle
      r="6"
      cy="6"
      cx="46"
      stroke="none"
    >
      <animate
        dur="1s"
        begin="0.3"
        values="0;1;0"
        attributeName="opacity"
        repeatCount="indefinite"
      />
    </circle>
  </svg>
</template>
